### ISSUE TITLE
Saving Trained NBayes

### ISSUE THREAD

**Issue by michaelcjoseph** [oasic/nbayes#8]
Is there a particular way you recommend saving a nbayes object that has been trained? I have a large training set, and I'd like to avoid retraining the nbayes object every time I need to use it.

**Comment by oasic** [comment]
There's a #dump method that allows trained models to be stored in YAML:
  nbayes.dump("model.yml")
Then you can load the model using the from class method:
  nbayes = NBayes::Base.from("model.yml")
That's it!

**Comment by michaelcjoseph** [comment]
Thanks @oasic!
